# Development-specific Docker Compose configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_DB: bodda_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
      - ./scripts/seed-dev-data.sql:/docker-entrypoint-initdb.d/02-seed-dev-data.sql

  backend:
    build:
      target: development
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/bodda_dev?sslmode=disable
      - LOG_LEVEL=debug
      - ENABLE_PROFILING=true
      - ENABLE_METRICS=true
      - WATCH_FILES=true
    volumes:
      - .:/app
      - /app/tmp
      - /app/bin
      - go_mod_cache:/go/pkg/mod
    command: ["air", "-c", ".air.toml"]

  frontend:
    build:
      target: development
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

  # Development tools
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - bodda-network
    depends_on:
      - postgres

volumes:
  postgres_dev_data:
  go_mod_cache:
  frontend_node_modules: